language: ruby
rvm:
 - 2.7.1

install:
 - bundle update --bundler
 - bundle install

services:
 - postgresql

script:
 — bundle exec rails db:create

 script:
 — bundle exec rails db:migrate

 script:
 - bundle exec rspec
